### ISSUE TITLE
Are the submitted articles 'static'?

### ISSUE THREAD

**Issue by eine** [openjournals/openjournals.github.io#4]
From https://github.com/openjournals/joss-reviews/issues/1346#issuecomment-475979876

> A side-question about JOSS: are the submitted articles 'static' or is it possible to update them every once in a while?

**Comment by arfon** [comment]
@1138-4EB they're generally considered to be static. If there is a problem with an article (e.g. an author name is incorrect) then we can make updates. Otherwise, larger changes are not supported.

Follow-up publications about future releases of the same software are supported though (this has happened in the past)
